---
title: "Snowplow 21.08 North Cascades"
date: "2021-08-28"
sidebar_position: 99980
---

### Recommended Stack

Please note, the `x` indicates that we recommend always being on the latest patched version. Components which have been updated since the last release are **highlighted**.

Log4j Advisory

Following the [Log4j advisory in December 2021](https://discourse.snowplowanalytics.com/t/advisory-impact-of-log4j-2-cve-2021-44228-on-snowplow-components/6065), we have updated a number of recommended component versions within the 21.08 North Cascades release. These are **highlighted** and with an \* next to the component name.

#### AWS

<table class="has-fixed-layout"><tbody><tr><td class="has-text-align-center" data-align="center"><span class="has-inline-color has-luminous-vivid-orange-color"><strong>Stream Collector</strong>*</span></td><td class="has-text-align-center" data-align="center"><span class="has-inline-color has-luminous-vivid-orange-color"><strong>Stream Enrich</strong>*</span></td><td class="has-text-align-center" data-align="center">Dataflow Runner</td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Sqs2Kinesis</span></strong></td></tr><tr><td class="has-text-align-center" data-align="center"><a href="http://github.com/snowplow/stream-collector/releases">v2.4.5</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/stream-enrich/releases">v2.0.5</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/dataflow-runner/releases">v0.5.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/sqs2kinesis/releases/tag/1.0.0" target="_blank" rel="noreferrer noopener">v1.0.x</a></td></tr></tbody></table>

<table class="has-fixed-layout"><tbody><tr><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-luminous-vivid-orange-color">S3 Loader*</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">RDB Loader</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Snowflake Loader</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-luminous-vivid-orange-color">Elasticsearch<br/>Loader*</span></strong></td></tr><tr><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-s3-loader/releases">v2.1.3</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-rdb-loader/releases">v1.1.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/snowplow-snowflake-loader/releases">v0.8.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-elasticsearch-loader/releases">v1.0.5</a></td></tr></tbody></table>

#### GCP

<table class="has-fixed-layout"><tbody><tr><td class="has-text-align-center" data-align="center"><span class="has-inline-color has-luminous-vivid-orange-color"><strong>Stream Collector</strong>*</span></td><td class="has-text-align-center" data-align="center"><span class="has-inline-color has-luminous-vivid-orange-color"><strong>Beam Enrich</strong>*</span></td><td class="has-text-align-center" data-align="center"><span class="has-inline-color has-luminous-vivid-orange-color"><strong>Enrich PubSub</strong>*</span></td><td class="has-text-align-center" data-align="center">GCS Loader</td><td class="has-text-align-center" data-align="center">BigQuery Loader</td></tr><tr><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/stream-collector/releases">v2.4.5</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/enrich/releases">v2.0.5</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/enrich/releases">v2.0.5</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/snowplow-google-cloud-storage-loader/releases">v0.3.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/snowplow-bigquery-loader/releases">v0.6.x</a></td></tr></tbody></table>

#### Iglu

<table class="has-fixed-layout"><tbody><tr><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Iglu Server</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">igluctl</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Iglu Central</span></strong></td></tr><tr><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/iglu-server/releases">v0.7.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/igluctl/releases/">v0.8.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/iglu-central/releases" target="_blank" rel="noreferrer noopener">R125</a></td></tr></tbody></table>

#### **Trackers**

<table class="has-fixed-layout"><tbody><tr><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">JS (Web &amp; Node)</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Android</span></strong></td><td class="has-text-align-center" data-align="center"><span class="has-inline-color has-vivid-purple-color"><strong>iOS</strong></span></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">React Native</span></strong></td><td class="has-text-align-center" data-align="center">Java</td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">.NET</span></strong></td><td class="has-text-align-center" data-align="center">Python</td></tr><tr><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-javascript-tracker/releases">v3.1.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-android-tracker/releases">v2.2.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-objc-tracker/releases">v2.2.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow-incubator/snowplow-react-native-tracker/releases">v1.0.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-java-tracker/releases">v0.9.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-dotnet-tracker/releases">v1.1.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-python-tracker/releases">v0.9.x</a></td></tr></tbody></table>

<table class="has-fixed-layout"><tbody><tr><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">AMP</span></strong></td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Unity</span></strong></td><td class="has-text-align-center" data-align="center">PHP</td><td class="has-text-align-center" data-align="center"><strong><span class="has-inline-color has-vivid-purple-color">Golang</span></strong></td><td class="has-text-align-center" data-align="center">Scala</td><td class="has-text-align-center" data-align="center">Ruby</td><td class="has-text-align-center" data-align="center">C++</td></tr><tr><td class="has-text-align-center" data-align="center"><a href="/docs/migrated/collecting-data/collecting-from-own-applications/google-amp-tracker/">v1.0.3</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-unity-tracker/releases">v0.5.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-php-tracker/releases">v0.4.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-golang-tracker/releases">v2.4.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-scala-tracker/releases">v1.0.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-ruby-tracker/releases">v0.6.x</a></td><td class="has-text-align-center" data-align="center"><a href="https://github.com/snowplow/snowplow-cpp-tracker/releases">v0.1.x</a></td></tr></tbody></table>

#### **Data Model**ing

##### SQL Runner

<table class="has-fixed-layout"><tbody><tr><td>Redshift web model</td><td>BigQuery web model</td><td>Snowflake web model</td></tr><tr><td><a href="https://github.com/snowplow/data-models/releases">v1.2.x</a></td><td><a href="https://github.com/snowplow/data-models/releases">v1.0.x</a></td><td><a href="https://github.com/snowplow/data-models/releases">v1.0.x</a></td></tr></tbody></table>

<table class="has-fixed-layout"><tbody><tr><td><strong><span class="has-inline-color has-vivid-purple-color">Redshift mobile model</span></strong></td><td><strong><span class="has-inline-color has-vivid-purple-color">BigQuery mobile model</span></strong></td><td><strong><span class="has-inline-color has-vivid-purple-color">Snowflake mobile model</span></strong></td></tr><tr><td><a href="https://github.com/snowplow/data-models/releases">v1.1.x</a></td><td><a href="https://github.com/snowplow/data-models/releases">v1.1.x</a></td><td><a href="https://github.com/snowplow/data-models/releases">v1.1.x</a></td></tr></tbody></table>

<table class="has-fixed-layout"><tbody><tr><td>SQL Runner</td></tr><tr><td><a href="https://github.com/snowplow/sql-runner/releases">v0.9.x</a></td></tr></tbody></table>

##### dbt

<table class="has-fixed-layout"><tbody><tr><td><strong><span class="has-inline-color has-vivid-purple-color">dbt-snowplow-web</span></strong></td><td><strong><span class="has-inline-color has-vivid-purple-color">dbt-snowplow-utils</span></strong></td><td><strong><span class="has-inline-color has-vivid-purple-color">dbt</span></strong></td></tr><tr><td><a href="https://github.com/snowplow/dbt-snowplow-web/releases" target="_blank" rel="noreferrer noopener">v0.2.x</a></td><td><a href="https://github.com/snowplow/dbt-snowplow-utils/releases" target="_blank" rel="noreferrer noopener">v0.2.x</a></td><td><a href="https://github.com/dbt-labs/dbt/releases">v0.19.x</a></td></tr></tbody></table>

#### **Testing**

<table class="has-fixed-layout"><tbody><tr><td><strong>Mini</strong></td><td><strong><span class="has-inline-color has-vivid-purple-color">Micro</span></strong></td></tr><tr><td><a href="https://github.com/snowplow/snowplow-mini/releases">v0.12.x</a></td><td><a href="https://github.com/snowplow-incubator/snowplow-micro/releases">v1.2.x</a></td></tr></tbody></table>

#### Analytics SDKs

<table class="has-fixed-layout"><tbody><tr><td>Scala</td><td>JavaScript</td><td>Python</td><td>.NET</td><td><strong><span class="has-inline-color has-vivid-purple-color">Golang</span></strong></td></tr><tr><td><a href="https://github.com/snowplow/snowplow-python-analytics-sdk/releases">v2.1.x</a></td><td><a href="https://github.com/snowplow-incubator/snowplow-js-analytics-sdk/releases">v0.3.0</a></td><td><a href="https://github.com/snowplow/snowplow-python-analytics-sdk/releases">v0.2.x</a></td><td><a href="https://github.com/snowplow/snowplow-dotnet-analytics-sdk/releases">v0.2.x</a></td><td><a href="https://github.com/snowplow/snowplow-golang-analytics-sdk/releases" target="_blank" rel="noreferrer noopener">v0.1.x</a></td></tr></tbody></table>

We hope that the above provides clarity on our recommended stack, however if you have any questions or feedback please reach out to us on [discourse](https://discourse.snowplowanalytics.com/).
