extends: existence
message: 'When you use a colon in a title or heading, capitalize the word that follows it.'
link: https://docs.microsoft.com/en-us/style-guide/punctuation/colons
nonword: true
level: warning
scope: heading
tokens:
  - ':\s[a-z]'
