extends: substitution
message: 'Is this a Snowplow component? Capitalize it.'
level: warning
ignorecase: false
scope:
  - sentence
  - paragraph
  - list
action:
  name: replace
swap:
  # bad: good
  'collector': Collector
  'enrich': Enrich
  'loader': Loader
