extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://developers.google.com/style/word-list'
level: error
ignorecase: false
action:
  name: replace
swap:
  '(snowplow|SnowPlow)': Snowplow
  '[Jj]avascript': JavaScript
