extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://developers.google.com/style/word-list'
level: warning
ignorecase: false
scope:
  - sentence
  - paragraph
  - list
action:
  name: replace
swap:
  '(snowplow|SnowPlow)': Snowplow
  '[Jj]avascript': JavaScript
  (?:github|Github): GitHub
  (?:kubernetes|k8s|K8s|K8S): Kubernetes
  (?:node.js|nodeJS|NodeJS|node.JS|Node.JS): Node.js
  (?:sql|Sql): SQL
  '[pP]ubsub': PubSub

  'context': entity
  'contexts': entities
  'e-commerce': ecommerce
  'eCommerce': ecommerce
