timeline
    title Sample media tracking scenario
    [0s] Video player appeared :  [0s] Call start media tracking : [0s] Track ready event : [30s] Ping event
    [40s] User started playing the video : [40s] Track play event : [60s] Ping event
    [65s] Ad started playing : [65s] Track ad break start : [65s] Track ad start : [70s] Track ad skip : [70s] Track ad break end
    [90s] Video resumed playing after ad : [90s] Ping event : [100s] Track end event
    [120s] Video player disappeared : [120s] Call end media tracking
